// What `tf2::BufferCore` costs in memory, in a native C++ process of its own.
//
// # Why this exists
//
// Of every memory comparison in this repository, exactly one has native C++ on
// the tf2 side — `dds_report`, fed by `ros/tf_tree_bench_ros`, and that one is
// dominated by rclcpp nodes rather than by either engine. `footprint`,
// `mp_bench`/`mp_consumer` and `shm_scaling` all reach tf2 through the Rust
// binding `tf_tree_tf2_sys`, so the process being weighed carries a Rust
// runtime, a Rust allocator and the shim in addition to tf2. And
// `docker/tf2/native_ratio.cpp` — the harness built precisely to remove
// cross-language bias from the *timing* comparison — measures no memory at all.
//
// So the apples-to-apples memory comparison did not exist. This is the tf2 half
// of it. The tf_tree half is `footprint`'s `mem-tf_tree` mode, unchanged, run as
// a separate Rust process.
//
// # Why two processes and not two modes of one program
//
// The same reason `just footprint` already runs its two modes as two
// invocations: building both engines in one process would let the first's freed
// chunks satisfy the second's requests, making whichever ran second look cheaper
// by an amount nobody can bound. Here it matters more, not less — one process
// would need both a Rust and a C++ runtime, and the comparison is supposed to be
// of engines.
//
// # Instruments
//
// Two, deliberately, because they answer different questions:
//
//   * **`mallinfo2`'s `uordblks + hblkhd`** — glibc's own accounting. C++
//     `operator new` bottoms out in `malloc`, so this measures the C++ and the
//     Rust engine on identical terms. `hblkhd` is not optional: tf_tree's arena
//     is a single allocation above glibc's 128 KiB mmap threshold and `uordblks`
//     alone would report it as almost nothing.
//   * **Pss from `/proc/self/smaps_rollup`** — what an operator sees in `top`.
//     `mallinfo2` cannot see it: an allocator can hold address space it has not
//     faulted, which is the whole subject of decision `0021`.
//
// The Pss reader is lifted verbatim in shape from
// `ros/tf_tree_bench_ros/include/tf_tree_bench_ros/measure.hpp:135-162`, the only
// native Pss reader in the repository. Same field, same file, same units.
//
// # The fixture
//
// The `.tfstream` written by `native_arena --dump-only`, which is generated by
// the same three lines as `fixture::spin_up` and `Tf2Fixture::load` — a
// constraint that file states and that keeps both engines on identical data. The
// cache duration is `HISTORY_SECS * 3.0 = 30 s`, matching `tf2.rs`'s
// `CACHE_SECS`, so tf2 retains everything and evicts nothing.

#include <tf2/buffer_core.hpp>
#include <geometry_msgs/msg/transform_stamped.hpp>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <malloc.h>
#include <sstream>
#include <string>
#include <vector>

namespace {

struct Sample {
  std::string parent, child;
  std::int64_t stamp_ns;
  double q[4];  // w x y z
  double t[3];
};

struct Stream {
  std::vector<Sample> statics;
  std::vector<Sample> dynamics;
};

// The same parser `native_ratio.cpp` and `native_scaling.cpp` use.
Stream load(const std::string &path) {
  Stream s;
  std::ifstream in(path);
  if (!in) {
    std::fprintf(stderr, "cannot open %s\n", path.c_str());
    std::exit(1);
  }
  std::string line;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#') continue;
    std::istringstream f(line);
    std::string kind;
    Sample x;
    f >> kind >> x.parent >> x.child;
    if (kind == "D") f >> x.stamp_ns;
    else x.stamp_ns = 0;
    f >> x.q[0] >> x.q[1] >> x.q[2] >> x.q[3] >> x.t[0] >> x.t[1] >> x.t[2];
    (kind == "S" ? s.statics : s.dynamics).push_back(std::move(x));
  }
  return s;
}

geometry_msgs::msg::TransformStamped to_msg(const Sample &x) {
  geometry_msgs::msg::TransformStamped m;
  m.header.frame_id = x.parent;
  m.child_frame_id = x.child;
  m.header.stamp.sec = static_cast<std::int32_t>(x.stamp_ns / 1000000000LL);
  m.header.stamp.nanosec = static_cast<std::uint32_t>(x.stamp_ns % 1000000000LL);
  m.transform.rotation.w = x.q[0];
  m.transform.rotation.x = x.q[1];
  m.transform.rotation.y = x.q[2];
  m.transform.rotation.z = x.q[3];
  m.transform.translation.x = x.t[0];
  m.transform.translation.y = x.t[1];
  m.transform.translation.z = x.t[2];
  return m;
}

// A real broadcaster stores its authority once. Constructing it per call was
// bias 4 in `tf2.md`: 20 characters is past libstdc++'s 15-byte SSO buffer, so a
// literal costs one heap allocation on every `setTransform` — charged to tf2,
// and it would land in the very counter this program reads.
const std::string kAuthority = "tf_tree_native_ratio";

// glibc's own accounting: in-use bytes across the sbrk heap and mmapped regions.
// Mirrors `footprint.rs`'s `heap_in_use()` exactly.
std::size_t heap_in_use() {
  const struct mallinfo2 mi = ::mallinfo2();
  return mi.uordblks + mi.hblkhd;
}

// Pss in KiB, or 0 if `/proc/self/smaps_rollup` is unreadable.
std::uint64_t self_pss_kib() {
  std::ifstream smaps("/proc/self/smaps_rollup");
  std::string line;
  while (std::getline(smaps, line)) {
    if (line.rfind("Pss:", 0) == 0) {
      std::istringstream f(line.substr(4));
      std::uint64_t kib = 0;
      f >> kib;
      return kib;
    }
  }
  return 0;
}

}  // namespace

int main(int argc, char **argv) {
  const std::string path = argc > 1 ? argv[1] : "target/native/fixture.tfstream";

  // Parse **before** the first measurement: the parsed `Stream` is the
  // harness's own memory, not tf2's, exactly as `mem_tf_tree` drops its
  // `PushSample` vector before snapshotting. Charging tf2 for the input it was
  // handed would be the same 29% error that file documents, in the other
  // direction.
  const Stream s = load(path);

  // Touch the allocator once before the baseline so glibc's first-use
  // bookkeeping is not charged to the engine.
  { std::string warm(1024, 'x'); (void)warm.size(); }

  const std::size_t heap_before = heap_in_use();
  const std::uint64_t pss_before = self_pss_kib();

  // 30 s, matching `tf2.rs`'s `CACHE_SECS = HISTORY_SECS * 3.0`, so nothing is
  // evicted and the comparison is over the same retained history.
  tf2::BufferCore buf(tf2::durationFromSec(30.0));
  for (const auto &x : s.statics) buf.setTransform(to_msg(x), kAuthority, true);
  for (const auto &x : s.dynamics) buf.setTransform(to_msg(x), kAuthority, false);

  const std::size_t heap_after = heap_in_use();
  const std::uint64_t pss_after = self_pss_kib();

  const std::size_t stored = s.dynamics.size();
  const std::size_t heap = heap_after - heap_before;

  std::printf("engine\ttf2\n");
  std::printf("heap_bytes\t%zu\n", heap);
  std::printf("pss_kib_delta\t%llu\n",
              static_cast<unsigned long long>(pss_after - pss_before));
  std::printf("pss_kib_total\t%llu\n", static_cast<unsigned long long>(pss_after));
  std::printf("samples_stored\t%zu\n", stored);
  std::printf("static_edges\t%zu\n", s.statics.size());
  // tf2 has no notion of a declared slot — it grows into what it is given. That
  // asymmetry is the whole point of the comparison, so the field is emitted as
  // `n/a` rather than omitted, or a reader diffing the two tables would think it
  // had been forgotten.
  std::printf("declared_slots\tn/a\n");
  std::printf("bytes_per_slot\tn/a\n");
  std::printf("bytes_per_sample\t%.1f\n",
              stored ? static_cast<double>(heap) / static_cast<double>(stored) : 0.0);

  // Keep the buffer alive across the measurement — a destructor running before
  // the second reading would report a fraction of the real cost.
  if (buf.allFramesAsString().empty()) std::fprintf(stderr, "empty tf2 buffer\n");
  return 0;
}
